# Generated by Django 4.2.1 on 2023-05-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_listitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='price_id',
            field=models.CharField(default='price_1N9FsTJgrzFtfn7Gy6NtNvSg', max_length=300),
            preserve_default=False,
        ),
    ]
