# Generated by Django 4.2.1 on 2023-05-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
