# Generated by Django 4.2.1 on 2023-05-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_fullorder_purchase_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullorder',
            name='product_ordered',
            field=models.ManyToManyField(through='products.Purchase', to='products.listitem'),
        ),
    ]
