# Generated by Django 4.2.1 on 2023-05-31 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productreview_posted_reviewreply_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewreply',
            name='secondary_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.reviewreply'),
        ),
    ]
